#!/bin/bash

# CRED2 camera startup script

# number of arguments to script
NBARGS_MIN=1
NBARGS_MAX=2


# ======================= PROCESS NAME =================================
pname=`basename "$0"`


EDTCONFFILE="/home/scexao/src/hardw-cred2/config/cred2_FGSetup_14bit.cfg"
SRCDIR="/home/scexao/src/hardw-cred2/src"



function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : CRED2 CAMERA STARTUP SCRIPT $(tput sgr0)"
echo " Full path name: $0"
echo "------------------------------------------------------------------------"
echo "  Start processes for CRED2 camera acquisition (server and acquisition)"
echo "  Processes are running in tmux sessions"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0 [-hHLNCc] <CAM number>"
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr0)"
echo "     $(tput bold)-h$(tput sgr0)          help"
echo ""
echo " $(tput bold)INPUT:$(tput sgr0)"
echo "     <CAM number>     camera number (0 or 1)"
echo "     <cmode>	    initial cropmode (defaults to 0)"
echo ""
echo "------------------------------------------------------------------------"
}


printHELP1 ()
{
    printf "%20s       CRED2 camera startup script\n" "$0" 
}


EXITSTATUS=0


function checkFile {
if [ -f $1 ]
  then
    echo "[$(tput setaf 2)$(tput bold)   OK   $(tput sgr0)] File $(tput bold)$1$(tput sgr0) found"
   else
    echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] File $(tput bold)$1$(tput sgr0) not found"
    EXITSTATUS=1
fi
}



function checkDir {
if [ -d $1 ]
  then
    echo "[$(tput setaf 2)$(tput bold)   OK   $(tput sgr0)] Directory $(tput bold)$1$(tput sgr0) found"
   else
    echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] Directory $(tput bold)$1$(tput sgr0) not found"
    EXITSTATUS=1
fi
}



function cmdexists()
{
  command -v "$1" >/dev/null 2>&1
}



function checkCommand {
if cmdexists $1; then
    echo "[$(tput setaf 2)$(tput bold)   OK   $(tput sgr0)] Command $(tput bold)$1$(tput sgr0) found"
else
    echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] Command $(tput bold)$1$(tput sgr0) not installed.  Aborting."; EXITSTATUS=1;
fi
}





# ================= OPTIONS =============================
# Transform long options to short ones
singlelinehelp=0
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--help1") 
set -- "$@" "-h" 
singlelinehelp=1;
;;
    *)        set -- "$@" "$arg"
  esac
done



while getopts :hH:L:N:Cc FLAG; do
  case $FLAG in
    h)  #show help
      if [ "$singlelinehelp" -eq "0" ]; then
      printHELP
      else
      printHELP1
      fi
      exit
      ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      ;;
  esac
done



shift $((OPTIND-1))  #This tells getopts to move on to the next argument.
### End getopts code ###
if [ "$1" = "help" ] || [ "$#" -lt $NBARGS_MIN ] || [ "$#" -gt $NBARGS_MAX ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi




# ======================= CHECK REQUIRED FILES =================================
echo ""
checkFile ${EDTCONFFILE}




# ============================= CHECK IF COMMAND EXISTS ==========================
checkCommand tmux




if [ $EXITSTATUS -eq 1 ]; then
echo ""
echo "$(tput setaf 1)$(tput bold) REQUIRED FILES, COMMANDS NOT FOUND: EXITING $(tput sgr0)"
echo ""
exit
else
echo ""
fi





# ======================= SCRIPT CODE STARTS HERE =================================


unit="$1"
cropmode="$2"
if [ -z "${cropmode}" ]; then
	cropmode="0"
fi

echo "STARTING CRED2 CAMERA UNIT $unit using initial cropmode $cropmode"

/opt/EDTpdv/initcam -c 0 -u $unit -f ${EDTCONFFILE}

tmux new-session -d -s ircam${unit}ctrl
tmux new-session -d -s ircam${unit}run


tmux send-keys -t ircam${unit}ctrl "" C-c
tmux send-keys -t ircam${unit}ctrl "" C-c
tmux send-keys -t ircam${unit}run "" C-c
tmux send-keys -t ircam${unit}run "" C-c


tmux send-keys -t ircam${unit}ctrl "cd ${SRCDIR}" C-m
tmux send-keys -t ircam${unit}run "cd ${SRCDIR}" C-m
sleep 0.5

tmux send-keys -t ircam${unit}ctrl "./ircamserver -u ${unit}" C-m


tmux send-keys -t ircam${unit}ctrl "setcrop ${cropmode}" C-m

#tmux send-keys -t ircam0ctrl "start" C-m



