#!/bin/sh

ISIO_ROOT=${MILK_ROOT}/src/ImageStreamIO


gcc imgtake.c cred2struct.c -o imgtake -I/opt/EDTpdv -I${ISIO_ROOT} -I${CACAO_ROOT}/src ${ISIO_ROOT}/ImageStreamIO.c /opt/EDTpdv/libpdv.a -Wall -lm -lpthread -ldl

gcc ircamserver.c cred2struct.c -o ircamserver -I/opt/EDTpdv /opt/EDTpdv/libpdv.a -lm -lpthread -ldl

